version: "3.7"
services:
  production:
    container_name: projeto_teste_amorim_production
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "5000:80"
      - "5001:443"