version: "3.7"
services:
  development:
    container_name: projeto_teste_amorim_development
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:80"
      - "3001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  production:
    container_name: projeto_teste_amorim_production
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "5000:80"
      - "5001:443"